# Site settings
title: Yoonsoyoung
email: hummingsy@gmail.com
url: https://yoonsoyoung.github.io
description: "Yoon soyoung's Portfolio"
keywords: "yoonsoyoung, Developer, web, app, ui designer"
skills: "Programming - Web/App Developer - UI Designer"
meta_author: Yoon SOYOUNG

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136 #yellow
  primary-rgb: "254,209,54" #"128,179,255"
  secondary: 323335 #navy black
  secondary-dark: 252628 #deep navyblack

# Footer settings
footer:
  copyright: YOONSOYOUNG
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:hummingsy@gmail.com
  - title: facebook
    url: http://www.facebook.com/yoon.soyoung.50
  - title: instagram
    url: http://www.instagram.com/5soo0young_2
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/yoonsoyoung

# Postal address (add as many lines as necessary)
address:
  - line: Gawngju, Republic of Korea
  # - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
